# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e22f064ce28078d105c40d7b8e0392bfcb6a7d827e3ce6201eddc1ff01ab1bcf6631d990ab68693352e6f6732fadb28eab355a8f285d7a3c237496a44eff0a9

test:
  secret_key_base: e7862df6c57ba4bf7ed39cfb13511146d169736ead6334c48a10d55c6632fcf2464f0ab49c2292284f18e3323feeeed36326b288f9ec5f346d1d02f65855b96e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
